events { }

http {
  client_max_body_size 1000M;
  # APP 1: Calculator (Port 80)
  server {
    listen 80;
    location / {
      proxy_pass http://shiny_front:3838;
      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "upgrade";
      proxy_set_header Host $host;
      proxy_read_timeout 900s;
    }
  }

  # APP 2: Visual Analytics (Port 81)
  server {
    listen 81;
    location / {
      proxy_pass http://shiny_front_analytics:3838;
      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "upgrade";
      proxy_set_header Host $host;
      proxy_read_timeout 900s;
    }
  }

  # APP 3: Data Exchange / CSV (Port 82)
  server {
    listen 82;
    location / {
      proxy_pass http://shiny_front_csv:3838;
      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "upgrade";
      proxy_set_header Host $host;
      proxy_read_timeout 900s;
    }
  }

  # APP 3: Geospatial Editor (Port 84)
  server {
    listen 84;
    location / {
      proxy_pass http://shiny_front_map:3838;
      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "upgrade";
      proxy_set_header Host $host;
      proxy_read_timeout 900s;
    }
  }

  # APP 4: Monte Carlo Simulator (Port 83)
  server {
    listen 83;
    location / {
      proxy_pass http://shiny_front_mc:3838;
      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "upgrade";
      proxy_set_header Host $host;
      proxy_read_timeout 900s;
    }
  }

  # APP 6: LTER-LIFE Anomaly Detector (Port 85)
  server {
    listen 85;
    location / {
      proxy_pass http://shiny_front_csv_advanced:3838;
      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "upgrade";
      proxy_set_header Host $host;
      proxy_read_timeout 900s;
    }
  }

  # APP 7: Advanced Visual Analytics (Port 87)
  server {
    listen 87;
    location / {
      proxy_pass http://shiny_front_analytics_advanced:3838;
      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "upgrade";
      proxy_set_header Host $host;
      proxy_read_timeout 900s;
    }
  }

  # APP 8: ML Trainer (Port 88)
  server {
    listen 88;
    location / {
      proxy_pass http://shiny_front_ml:3838;
      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "upgrade";
      proxy_set_header Host $host;
      proxy_read_timeout 900s;
    }
  }
}