server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        # This tells the Angular Nginx to route all 404s to index.html
        try_files $uri $uri/ /index.html;
    }
}