events {
    worker_connections 1024;
}

http {
    server {
        listen 80;
        location / {
            # FIX: Use the new hyphenated container name!
            proxy_pass http://shiny-front:3838;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
        }
    }
}