services:

  zookeeper:
    image: confluentinc/cp-zookeeper:6.1.1
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - 2181:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  broker:
    image: confluentinc/cp-enterprise-kafka:6.1.1
    hostname: broker
    container_name: broker
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
      - 9101:9101
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: EXTERNAL:PLAINTEXT,INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: EXTERNAL://broker:29092,INTERNAL://localhost:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_CREATE_TOPICS: "input, output"

  shiny_front:
    image: rstudio/rjava:0.1.0
    build: .
    container_name: shiny_front
    volumes:
      - ./shiny_front.r:/home/shiny_front.r
    ports:
      - 8080:8787
    environment:
      USER: user
      PASSWORD: password

  shiny_back:
    image: rstudio/rjava:0.1.0
    build: .
    container_name: shiny_back
    volumes:
      - ./shiny_back.r:/home/shiny_back.r
    ports:
      - 8180:8787
    environment:
      USER: user
      PASSWORD: password

