library(shiny)
library(leaflet)
library(jsonlite)
library(kafka)
library(shinyjs)

ui <- fluidPage(
  useShinyjs(),
  titlePanel("Benchmark 3: Geospatial Editor"),
  sidebarLayout(
    sidebarPanel(
      h4("Map Controls"),
      p("Click anywhere on the map to drop a collaborative pin!"),
      hr(),
      uiOutput("session_info_ui"),
      hr(),
      uiOutput("last_update_ui")
    ),
    mainPanel(
      # Leaflet requires a set height to render properly
      leafletOutput("map", height = "600px")
    )
  )
)

server <- function(input, output, session) {
  identity <- reactive({
    query <- parseQueryString(session$clientData$url_search)
    list(userId = if (!is.null(query$userId)) query$userId else "anonymous", sessionId = if (!is.null(query$sessionId)) query$sessionId else NULL)
  })
  routingKey <- reactive({ id <- identity(); if (!is.null(id$sessionId)) id$sessionId else id$userId })
  
  state <- reactiveValues(connected = FALSE, consumer = NULL, producer = NULL, permission = "EDITOR", last_sender = NULL)

  output$session_info_ui <- renderUI({ p("Role: ", strong(state$permission)) })

  # Render the initial base map (Centered roughly on Switzerland)
  output$map <- renderLeaflet({
    leaflet() %>% 
      addTiles() %>% 
      setView(lng = 8.5417, lat = 47.3769, zoom = 7)
  })

  # --- SETUP KAFKA ---
  observe({
    if (state$connected) return()
    tryCatch({
      query <- parseQueryString(session$clientData$url_search)
      state$permission <- if (!is.null(query$permission)) query$permission else "EDITOR"
      broker <- "kafka:9092"
      state$consumer <- Consumer$new(list("bootstrap.servers" = broker, "group.id" = paste0("front_map_", sample(10000:99999, 1)), "auto.offset.reset" = "latest", "enable.auto.commit" = "true"))
      state$consumer$subscribe("output")
      if (state$permission %in% c("EDITOR", "OWNER")) state$producer <- Producer$new(list("bootstrap.servers" = broker))
      state$connected <- TRUE
    }, error = function(e) { print(e$message) })
  })

  # --- SEND CLICK COORDINATES TO KAFKA ---
  observeEvent(input$map_click, {
    req(state$connected, !is.null(state$producer))
    # input$map_click contains $lat and $lng automatically generated by Leaflet!
    click <- input$map_click 
    
    payload <- list(lat = click$lat, lng = click$lng, sender = identity()$userId, role = state$permission)
    state$producer$produce("input", toJSON(payload, auto_unbox = TRUE), key = routingKey())
  })
  
  # --- RECEIVE PINS & UPDATE MAP ---
  poll_trigger <- reactivePoll(500, session, checkFunc = function() as.numeric(Sys.time()), valueFunc = function() as.numeric(Sys.time()))
  
  observe({
    poll_trigger()
    req(state$connected, !is.null(state$consumer))
    messages <- state$consumer$consume(100)
    if (length(messages) > 0) {
      for (m in messages) {
        if (!is.null(m$key) && m$key == routingKey()) {
          data <- fromJSON(m$value)
          
          if (!is.null(data$type) && data$type == "SYSTEM" && !is.null(data$targetUser) && data$targetUser == identity()$userId) {
              state$permission <- data$newRole
              state$producer <- if (data$newRole %in% c("EDITOR", "OWNER")) Producer$new(list("bootstrap.servers" = "kafka:9092")) else NULL
          } else if (!is.null(data$pois)) {
            
            # Extract dataframe and dynamically redraw the map markers
            pois <- as.data.frame(data$pois)
            state$last_sender <- data$sender
            
            # Use leafletProxy to update the existing map without full reload
            leafletProxy("map") %>% 
              clearMarkers() %>% 
              addMarkers(data = pois, ~lng, ~lat, popup = ~paste("Placed by:", sender))
          }
        }
      }
    }
  })

  output$last_update_ui <- renderUI({ req(state$last_sender); p(em(paste("Last pin dropped by:", state$last_sender))) })
}
shinyApp(ui = ui, server = server)